apiVersion: v1
kind: Service
metadata:
  name: cloud-doc-processor-service
spec:
  type: NodePort
  selector:
    app: cloud-doc-processor
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007
